# Generated by Django 4.2.3 on 2024-02-20 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0016_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_design_star', models.IntegerField(blank=True, null=True)),
                ('ui_design_comment', models.CharField(blank=True, max_length=999, null=True)),
                ('bug_star', models.IntegerField(blank=True, null=True)),
                ('bug_comment', models.CharField(blank=True, max_length=999, null=True)),
                ('features_star', models.IntegerField(blank=True, null=True)),
                ('features_comment', models.CharField(blank=True, max_length=999, null=True)),
                ('performance_star', models.IntegerField(blank=True, null=True)),
                ('performance_comment', models.CharField(blank=True, max_length=999, null=True)),
                ('expected_outcome_star', models.IntegerField(blank=True, null=True)),
                ('expected_outcome_comment', models.CharField(blank=True, max_length=999, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
